spring:
  application:
    name: member-service
  datasource:
    url: jdbc:mariadb://localhost:3306/mydatabase
    username: myuser
    password: mypassword
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: false

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: OFF
    org.hibernate.type.descriptor.sql.BasicBinder: OFF

